const PRIMARY = "#B1E4F4";
const PRIMARY_DARK1 = "#0FABCD";
const PRIMARY_DARK2 = "#7B8EAB";
const SECONDARY = "#3186EA";
const THIRD = "#26305C";
const CONTRAST = "#202444";
const INACTIVE_CONTRAST = "#F4F4F4";
const ERROR = "#db3125";
const SUCCESS = "#26A81F";
const OVERLAY = "rgba(45, 35, 35, 0.5)";
const INFO = "#20639B";
const FULLY_TRANSPARENT_OVERLAY = "rgba(0, 0, 0, 0)";

const colors = {
  PRIMARY,
  SECONDARY,
  THIRD,
  CONTRAST,
  INACTIVE_CONTRAST,
  ERROR,
  SUCCESS,
  OVERLAY,
  INFO,
  PRIMARY_DARK1,
  PRIMARY_DARK2,
  FULLY_TRANSPARENT_OVERLAY,
};

export default colors;
